---
version: "{build}"
clone_depth: 5
init:
  # Remove any ENV settings related to OpenSSL-Win
  - set SSL_CERT_DIR=
  - set SSL_CERT_FILE=
  - set OPENSSL_CONF=
  - set OPENSSL_DIR=
  # Flag for whether build is local or running in Appveyor
  - set AV_BUILD=true
  # Minimize path so bash conflicts don't arise
  - set base_path=C:\ruby24-x64\bin;C:\Program Files\7-Zip;C:\Program Files\AppVeyor\BuildAgent;C:\Program Files\Git\cmd;C:\Windows\system32;C:\Program Files;C:\Windows

  - git clone -q --depth=5  --branch=master https://github.com/oneclick/rubyinstaller2.git    C:\ri2
  - git clone -q --depth=5  --no-tags --branch=master https://github.com/ConnorAtherton/rb-readline.git C:\rb-readline
  - set PATH=%base_path%

install:
  - git clone -q --depth=5  --no-tags --branch=trunk  https://github.com/ruby/ruby.git                  C:\projects\ruby-loco\src\ruby
  # below 3 lines just for special checkouts
  #- cd \projects\ruby-loco\src\ruby
  #- git checkout 72f88ebcc1
  #- cd \projects\ruby-loco
  # Update MSYS2 / MinGW and install OpenSSL 1.1.0 & GDBM 1.10
  - av_install\trunk_msys2.cmd
  # Tests are happier with a git path that doesn't contain a space
  - mklink /d C:\projects\ruby-loco\git "C:\Program Files\Git"

build_script:
  # builds, installs and tests
  - pkg_build_64.cmd
  - echo Done with pkg_build

test_script:
  # processes test logs, outputs 'Test Results', saves artifacts
  - echo In test_script
  - ruby test_script.rb
  - set TEST_SCRIPT=done

on_finish:
  # Run test_script if tests (in pkg_build_64.cmd) timed out and test_script.rb didn't run
  - echo In on_finish
  - if "%TEST_SCRIPT%" NEQ "done" ( ruby test_script.rb )

cache:
  - C:\projects\ruby-loco\bundled_gems
