name: ruby-loco
on:
  push:
    branches:
      - 'actions'
#  schedule:
#  - cron: '0 3,9,16 * * *'

jobs:
  mingw:
    strategy:
      fail-fast: false
    runs-on: windows-2019
    env:
      APPVEYOR: 'True'

    steps:
      - name: Cache - .downloaded-cache
        uses: actions/cache@v1
        with:
          path: .downloaded-cache
          key: dl-cache-win-mingw-${{ github.sha }}
          restore-keys: |
            dl-cache-win-mingw

      - name: git config
        run: |
          git config --system core.autocrlf false
          git config --system core.eol lf

      - name: Checkout ruby-loco
        uses: actions/checkout@v2

      - name: Checkout ruby
        uses: actions/checkout@v2
        with:
          repository: ruby/ruby
          path: ruby

      - name: Checkout rubyinstaller2
        uses: actions/checkout@v2
        with:
          repository: oneclick/rubyinstaller2
          path: rubyinstaller2


      - name: Set up Ruby & MSYS2
        uses: MSP-Greg/actions-ruby@master
        with:
          ruby-version: 2.7.x
          base: update
          mingw: gdbm gmp libffi libyaml openssl ragel readline
          msys2: automake1.16 bison

      - name: build & install
        run:  ./1_0_build_install_64.ps1

      - name: test
        run:  ./2_0_test.ps1

      - name: upload asset
        timeout-minutes: 5
        uses: ./.github/actions/upload-binary
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          ruby_path: ./ruby-mingw
